---
title: "Epicardium_2"
author: "Clay Carey"
date: "2023-02-16"
output: html_document
---

```{r}
library(ggplot2)
library(Seurat)
library(dittoSeq)
library(Nebulosa)
library(dplyr)
library(gridExtra)
library(viridis)
heart_filtered <- readRDS(file = 'heart_filtered.rds')
```

```{r}
DimPlot(heart_filtered, label = TRUE)
```

```{r}
epicardium <- subset(heart_filtered, idents = c(5,10,21))
```


```{r}
cols <- c("#8dd3c7", "#d9d9d9","#fb8072", "#8DF2C1", "#80b1d3", "#fdb462")
DefaultAssay(epicardium) <- "integrated"
epicardium <- ScaleData(epicardium)
epicardium <- RunPCA(epicardium, npcs = 30 )
epicardium <- RunUMAP(epicardium, dims = 1:27, min.dist = 0.15, n.epochs = 200)
epicardium <- FindNeighbors(epicardium, dims = 1:27, reduction = 'pca', n.tree = 500 )
epicardium <- FindClusters(epicardium, resolution = 0.15)
DimPlot(epicardium, label = TRUE, pt.size = 1, cols = cols, label.size = 6) +NoLegend() +NoAxes()
```


```{r}
ditto_color <- c("#61A2DE","#61A2DE","#61A2DE","#D39234","#D39234","#D39234")
shades_of_grey <- c("#F2F2F2", "#C9C9C9", "#A6A6A6", "#7E7E7E", "#4F4F4F")


my_levels <- c("zebrafish_uninjured","zebrafish_3dpi","zebrafish_14dpi","medaka_uninjured","medaka_3dpi","medaka_14dpi")
epicardium_filtered@meta.data$group <- factor(x = epicardium_filtered@meta.data$group, levels = my_levels)

dittoFreqPlot(epicardium_filtered, "seurat_clusters", sample.by = 'sample', group.by = 'group',vars.use = 2 ,color.panel = ditto_color, boxplot.color = '#4F4F4F', jitter.size = 1.5) + NoLegend() +  theme(axis.title.x=element_blank()) + theme(plot.title = element_blank()) + ylab("Percent of epicardial cells in cluster 2")

```


```{r}

vln_color <- c("#55DFD4","#69D5F8","#5192DC","#F7BC6D","#FCDA61","#FA8961")


vln1 <- VlnPlot(epicardium_filtered, features = c("col12a1a","col12a1b",'twist1b','postnb','fn1a','col1a1a','col1a2'), split.by = 'group', group.by = 'group', stack = TRUE, flip = TRUE, cols = vln_color)

vln2 <-  VlnPlot(epicardium_filtered, features = c('fn1a','fn1','col1a2','col1','col1a1a'), split.by = 'group', group.by = 'group', stack = TRUE, flip = TRUE, cols = vln_color)

vln3 <- VlnPlot(epicardium_filtered, features = 'nrg1', idents = 1, group.by = 'group')

vln2
vln1
vln3


```





```{r}
dittoFreqPlot(epicardium_filtered, "seurat_clusters", sample.by = 'sample', group.by = 'group',vars.use = 3 ,color.panel = ditto_color) + NoLegend() +  theme(axis.title.x=element_blank()) + theme(plot.title = element_blank())

VlnPlot(epicardium_filtered, features ='nrg1', idents = '3', group.by = 'group')
```

```{r}
nrg1_pos <- subset(epicardium, subset = nrg1 > 0)
nrg1_cells <- nrg1_pos@meta.data
nrg1_cells$nrg1_pos <- "positive"
nrg1_cells$cell_id <- rownames(nrg1_cells)
nrg1_cells <- select(nrg1_cells, nrg1_pos, cell_id)
all_meta <- epicardium@meta.data
all_meta$cell_id <- row.names(all_meta)
all_meta <- left_join(all_meta, nrg1_cells, by = 'cell_id')
row.names(all_meta) <- all_meta$cell_id

all_meta <- select(all_meta, -cell_id)
all_meta

epi_filt_nrg <- epicardium
epi_filt_nrg@meta.data <- all_meta
epi_2_nrg <- subset(epi_filt_nrg, idents = 2)

dittoFreqPlot(epi_filt_nrg, "nrg1_pos", sample.by = 'sample', group.by = 'group',color.panel = vln_color,boxplot.color = '#4F4F4F', jitter.size = 1.5) + NoLegend() +  theme(axis.title.x=element_blank()) + theme(plot.title = element_blank()) + ylab("Percent of epicarial cells expressing nrg1")

dittoBoxPlot(epicardium, "nrg1", group.by = 'group',color.panel = vln_color) + NoLegend() +  theme(axis.title.x=element_blank()) + theme(plot.title = element_blank())
```

```{r}

ifnphi_pos <- subset(epicardium, subset = ifnphi1 > 0)
ifnphi_cells <- ifnphi_pos@meta.data
ifnphi_cells$ifnphi_pos <- "positive"
ifnphi_cells$cell_id <- rownames(ifnphi_cells)
ifnphi_cells <- select(ifnphi_cells, ifnphi_pos, cell_id)
all_meta <- epicardium@meta.data
all_meta$cell_id <- row.names(all_meta)
all_meta <- left_join(all_meta, ifnphi_cells, by = 'cell_id')
row.names(all_meta) <- all_meta$cell_id

all_meta <- select(all_meta, -cell_id)
all_meta

epi_filt_ifn <- epicardium
epi_filt_ifn@meta.data <- all_meta



dittoFreqPlot(epi_filt_ifn, "ifnphi_pos", sample.by = 'sample', group.by = 'group',color.panel = vln_color,boxplot.color = '#4F4F4F', jitter.size = 1.5) + NoLegend() +  theme(axis.title.x=element_blank()) + theme(plot.title = element_blank()) + ylab("Percent of epicarial cells expressing ifnphi")

```
```{r}


ifnphi_pos <- subset(endocardium, subset = ifnphi1 > 0)
ifnphi_cells <- ifnphi_pos@meta.data
ifnphi_cells$ifnphi_pos <- "positive"
ifnphi_cells$cell_id <- rownames(ifnphi_cells)
ifnphi_cells <- select(ifnphi_cells, ifnphi_pos, cell_id)
all_meta <- endocardium@meta.data
all_meta$cell_id <- row.names(all_meta)
all_meta <- left_join(all_meta, ifnphi_cells, by = 'cell_id')
row.names(all_meta) <- all_meta$cell_id

all_meta <- select(all_meta, -cell_id)
all_meta

endo_filt_ifn <- endocardium
endo_filt_ifn@meta.data <- all_meta



dittoFreqPlot(endo_filt_ifn, "ifnphi_pos", sample.by = 'sample', group.by = 'group',color.panel = vln_color,boxplot.color = '#4F4F4F', jitter.size = 1.5) + NoLegend() +  theme(axis.title.x=element_blank()) + theme(plot.title = element_blank()) + ylab("Percent of endocardial cells expressing ifnphi")


```

```{r}

aldh1a2_pos <- subset(epicardium_filtered, subset = aldh1a2 > 0)
aldh1a2_cells <- aldh1a2_pos@meta.data
aldh1a2_cells$aldh1a2_pos <- "positive"
aldh1a2_cells$cell_id <- rownames(aldh1a2_cells)
aldh1a2_cells <- select(aldh1a2_cells, aldh1a2_pos, cell_id)
all_meta <- epicardium_filtered@meta.data
all_meta$cell_id <- row.names(all_meta)
all_meta <- left_join(all_meta, aldh1a2_cells, by = 'cell_id')
row.names(all_meta) <- all_meta$cell_id

all_meta <- select(all_meta, -cell_id)
all_meta

epi_filt_aldh <- epicardium_filtered
epi_filt_aldh@meta.data <- all_meta
epi_2_aldh <- subset(epi_filt_aldh, idents = 2 )

dittoFreqPlot(epi_filt_aldh, "aldh1a2_pos", sample.by = 'sample', group.by = 'group',color.panel = ditto_color) + NoLegend() +  theme(axis.title.x=element_blank()) + theme(plot.title = element_blank())

dittoFreqPlot(epi_2_aldh, "aldh1a2_pos", sample.by = 'sample', group.by = 'group',color.panel = ditto_color) + NoLegend() +  theme(axis.title.x=element_blank()) + theme(plot.title = element_blank())

```

```{r}
library(clusterProfiler)
library(org.Dr.eg.db)
library(AnnotationHub)
epi_filtered_markers <- FindAllMarkers(epicardium_filtered, only.pos = TRUE, min.pct = 0.2)
top100 <- epi_filtered_markers %>% group_by(cluster) %>% top_n(n = 100, wt = avg_log2FC)
top100pval <- subset(top100, rowSums(top100[5] < 0.05) > 0)
top100pval
df <- top100pval[,7:6]
dfsample <- split(df$gene,df$cluster)
length(dfsample)
dfsample$`0` = bitr(dfsample$`0`, fromType="SYMBOL", toType="ENTREZID", OrgDb="org.Dr.eg.db")
dfsample$`1` = bitr(dfsample$`1`, fromType="SYMBOL", toType="ENTREZID", OrgDb="org.Dr.eg.db")
dfsample$`2` = bitr(dfsample$`2`, fromType="SYMBOL", toType="ENTREZID", OrgDb="org.Dr.eg.db")
dfsample$`3` = bitr(dfsample$`3`, fromType="SYMBOL", toType="ENTREZID", OrgDb="org.Dr.eg.db")
dfsample$`4` = bitr(dfsample$`4`, fromType="SYMBOL", toType="ENTREZID", OrgDb="org.Dr.eg.db")


genelist <- list("0" = dfsample$`0`$ENTREZID, 
                 "1" = dfsample$`1`$ENTREZID,
                 "2" = dfsample$`2`$ENTREZID,
                 "3" = dfsample$`3`$ENTREZID,
                 "4" = dfsample$`4`$ENTREZID
)

GOclusterplot <- compareCluster(geneCluster = genelist, fun = "enrichGO", OrgDb = "org.Dr.eg.db")
dotplot(GOclusterplot)
KEGGclusterplot <- compareCluster(geneCluster = genelist, fun = "enrichKEGG", organism = "zebrafish")
dotplot(KEGGclusterplot)
Pathwayclusterplot <- compareCluster(geneCluster = genelist, fun = "enrichPathway", organism = "zebrafish")
dotplot(Pathwayclusterplot)
GOclusterplot@compareClusterResult
```

```{r}
zf2md <- read.csv(file = "/Users/claytoncarey/Documents/Seurat/zf.cm.markers/zf2md.csv")

zf2md_collagens <- filter(zf2md, grepl("^col\\d+", zf_name) & type == 'ortholog_one2one' & score == 1)

zf2md_collagens

ortho_collagens <- zf2md_collagens$zf_name

zf2md_mmp <- filter(zf2md, grepl("^mmp\\d+", zf_name) & type == 'ortholog_one2one' & score == 1)

zf2md_mmp 

ortho_mmp <- zf2md_mmp$zf_name

zf2md_timp <- filter(zf2md, grepl("^timp\\d+", zf_name) & type == 'ortholog_one2one' & score == 1)

zf2md_timp 
```

```{r}
vln_color <- c("#55DFD4","#69D5F8","#5192DC","#F7BC6D","#FCDA61","#FA8961")

ortho_collagens <- c( "col28a2a", "col10a1a", "col1a1b",  "col1a2",   "col8a2",   "col12a1a", "col4a1",   "col9a3",   "col4a6",   "col18a1a", "col4a5", "col9a2",   "col6a2",   "col6a1",   "col9a1b",  "col5a2a",  "col11a2",  "col12a1b", "col9a1a",  "col2a1a",  "col1a1a",  "col10a1b" ,)


VlnPlot(epicardium, features = c(ortho_collagens,ortho_mmp,"timp2b"), split.by = 'group', group.by = 'group', stack = TRUE, flip = TRUE, cols = vln_color) + ggtitle("Epicardial cells") +NoLegend()

VlnPlot(endocardium, features = c(ortho_collagens_endo,ortho_mmp_endo,"timp2b"), split.by = 'group', group.by = 'group', stack = TRUE, flip = TRUE, cols = vln_color) + ggtitle("Endocardial cells") +NoLegend()

ortho_collagens_endo <- ortho_collagens[! ortho_collagens %in% "col9a1b"]
ortho_mmp_endo <- ortho_mmp[! ortho_mmp %in% "mmp16b"]

VlnPlot(epicardium, features = zf2md_timp, split.by = 'group', group.by = 'group', stack = TRUE, flip = TRUE, cols = vln_color)

```

```{r}
vln_color <- c("#55DFD4","#69D5F8","#5192DC","#F7BC6D","#FCDA61","#FA8961")


VlnPlot(epicardium_filtered, features = c(ortho_mmp,"timp2b",'timp2a'), split.by = 'group', group.by = 'group', stack = TRUE, flip = TRUE, cols = vln_color)
```

```{r}
DefaultAssay(epicardium) <- "RNA"
Idents(epicardium) <- "epicardium_type_class"
epi_markers <- FindAllMarkers(epicardium, only.pos = TRUE, min.pct = 0.2)
write.csv(epi_markers, file = 'epi_markers.csv')
```

```{r}
DefaultAssay(epicardium) <- "RNA"
VlnPlot(epicardium, features = 'thbs1b', split.by = 'group')
VlnPlot(endocardium, features = 'thbs1b', split.by = 'group')
VlnPlot(epicardium, features = 'ccn2a', split.by = 'group')
VlnPlot(epicardium, features = 'tmsb1', split.by = 'group')

VlnPlot(epicardium, features = 'nrg1', split.by = 'species')

```

```{r}
DimPlot(epicardium)
```

```{r}
DefaultAssay(epicardium) <- "RNA"
FeaturePlot_scCustom(epicardium, features = c("tcf21","fli1a","col1a2","col12a1a","ptx3a","col12a1b","postnb","postna","sox7"))
```

```{r}
cols <- c("#8dd3c7", "#d9d9d9","#fb8072", "#8DF2C1", "#80b1d3", "#fdb462")

DimPlot(epicardium, group.by = "epicardium_class", cols = cols,label =TRUE, pt.size = .5) + NoLegend() +NoAxes() +ggtitle("")
```
```{r}
epicardium@meta.data <- mutate(epicardium@meta.data, epicardium_class = case_when(
  seurat_clusters == 0 ~ "cEP1",
  seurat_clusters == 1 ~ "cEP2",
  seurat_clusters == 2 ~ "fEP",
  seurat_clusters == 3 ~ "zEP"
))

epicardium@meta.data <- mutate(epicardium@meta.data, epicardium_type = case_when(
  seurat_clusters == 0 ~ "other",
  seurat_clusters == 1 ~ "other",
  seurat_clusters == 2 ~ "fEP",
  seurat_clusters == 3 ~ "other"
))
epicardium@meta.data <- mutate(epicardium@meta.data, epicardium_type_class = case_when(
  seurat_clusters == 0 ~ "cEP",
  seurat_clusters == 1 ~ "cEP",
  seurat_clusters == 2 ~ "fEP",
  seurat_clusters == 3 ~ "zEP"
))

```

```{r}
Idents(epicardium) <- "epicardium_class"
dittoFreqPlot(epicardium,"epicardium_class", sample.by = 'sample', group.by = 'group',color.panel = vln_color,boxplot.color = '#4F4F4F', jitter.size = 1.5, vars.use = "fEP") + NoLegend() +  theme(axis.title.x=element_blank()) + theme(plot.title = element_blank()) + ylab("Percent of epicarial cells")

dittoFreqPlot(epicardium,"epicardium_class", sample.by = 'sample', group.by = 'group',color.panel = vln_color,boxplot.color = '#4F4F4F', jitter.size = 1.5, vars.use = "zEP") + NoLegend() +  theme(axis.title.x=element_blank()) + theme(plot.title = element_blank()) + ylab("Percent of epicarial cells")
```

```{r}
epi_dotplot_markers <- c('tcf21',')
```

```{r}
VlnPlot(epicardium, features = 'adam8a', split.by = 'group', cols = vln_color)
```
```{r}
epi_markers <- c("col12a1a","col11a1b","col12a1b",'col11a1a','postna','postnb','fn1a','twist1b','snai2','twist1a','ptx3a',"vim",'cdh2','aldh1a2','vcp')

VlnPlot(epicardium, features = epi_markers, split.by = "group", stack = TRUE, flip = TRUE, cols = vln_color)
```

```{r}

angiogenic <- c('aldh1a2','angptl2b','angptl1a','angpt1','vegfaa','vegfc','vegfab','vegfd', "cxcl8a")

VlnPlot(epicardium, features = angiogenic, split.by = "group", stack = TRUE, flip = TRUE, cols = vln_color) + NoLegend()
VlnPlot(endocardium, features = angiogenic, split.by = "group", stack = TRUE, flip = TRUE, cols = vln_color)

```

```{r}
VlnPlot(epicardium, features = neg_angio, split.by = "group", stack = TRUE, flip = TRUE, cols = vln_color)

```

```{r}
epi_dot_markers <- c('tcf21','tbx18', 'snai2', 'twist1b')
DotPlot(epicardium, features = epi_dot_markers, scale = TRUE) +
  geom_point(aes(size=pct.exp), shape = 21, colour="black", stroke=0.5) +
  scale_colour_viridis(option="inferno") +
  guides(size=guide_legend(override.aes=list(shape=21, colour="black", fill="white"))) + theme(axis.text.x =    element_text(angle =45,hjust = 1)) + theme(legend.title = element_text( size = 8))
```

```{r}
fp1 <- FeaturePlot_scCustom(epicardium, features = 'col12a1a') + NoAxes()
fp2 <- FeaturePlot_scCustom(epicardium, features = 'col11a1a') + NoAxes()
fp3 <- FeaturePlot_scCustom(epicardium, features = 'twist1b') + NoAxes()
fp4 <- FeaturePlot_scCustom(epicardium, features = 'postnb') + NoAxes()
fp5 <- FeaturePlot_scCustom(epicardium, features = 'col12a1b') + NoAxes()
fp6 <- FeaturePlot_scCustom(epicardium, features = 'fn1a') + NoAxes()
grid.arrange(fp1,fp2,fp3,fp4,fp5,fp6, ncol = 3 , nrow = 2)
```

```{r}
FeaturePlot_scCustom(heart_filtered, features = 'ifnphi1')
```

Genes differently regulated in zebrafish and medaka

zebrafish upregulated - hapln1a,hapln1b