---
title: "Myocardium Analysis"
author: "Clay Carey"
date: "2023-03-01"
output: pdf_document
---

```{r}
library(ggplot2)
library(Seurat)
library(dittoSeq)
library(Nebulosa)
library(dplyr)
library(gridExtra)
library(viridis)
library(scCustomize)
```

```{r}
heart_filtered <- readRDS(file = "heart_filtered.rds")
```

```{r}
DimPlot(heart_filtered, label = TRUE)
```

```{r}
DefaultAssay(heart_filtered) <- 'RNA'
FeaturePlot_scCustom(heart_filtered, features  = c('myl7','actc1a','cmlc1','ttn.2'))
```
```{r}
vln_color <- c("#55DFD4","#69D5F8","#5192DC","#F7BC6D","#FCDA61","#FA8961")

myocardium <- subset(heart_filtered, idents = c(2,3,7,8,14,19))
DefaultAssay(myocardium) <- "integrated"
myocardium <- ScaleData(myocardium, assay = 'integrated' )
myocardium <- RunPCA(myocardium, npcs = 30 )
myocardium <- RunUMAP(myocardium, dims = 1:27, min.dist = 0.1, n.epochs = 200)
myocardium <- FindNeighbors(myocardium, dims = 1:30, reduction = 'pca', n.tree = 500 )
myocardium <- FindClusters(myocardium, resolution = 0.2, algorithm = 2)
DimPlot(myocardium, label = TRUE, pt.size = 1, label.size = 6) +NoLegend() +NoAxes()
DimPlot(myocardium, group.by = 'group', cols = vln_color)
```
]

```{r}
DefaultAssay(myocardium) <- 'RNA'
FeaturePlot_scCustom(myocardium, features = c('pcna','cdc45','mcm5','cdca7a'))
FeaturePlot_scCustom(myocardium, features = 'tbx5a')
FeaturePlot_scCustom(myocardium, features = 'gata4')
VlnPlot(myocardium, features = 'tnnc2', split.by = 'group')
VlnPlot(myocardium, features = g2m.genes , split.by = 'group', stack = TRUE, flip = TRUE, cols = vln_color)
```


```{r}

DefaultAssay(myocardium) <- "RNA"
cc_markers <- read.csv(file = '/Users/claytoncarey/Documents/Seurat/ccmarkers.csv')
s.genes <- cc_markers$s
g2m.genes <- cc_markers$g2m
myocardium <- CellCycleScoring(myocardium, s.features = s.genes, g2m.features = g2m.genes, set.ident = FALSE)

DimPlot(myocardium, group.by = 'Phase')

head(myocardium)
```
```{r}
head(myocardium)
```

```{r}
zf_myocardium <- subset(myocardium, subset = species == 'zebrafish')
DefaultAssay(zf_myocardium) <- "RNA"
zf_myocardium <- DietSeurat(zf_myocardium, scale.data = FALSE, counts = TRUE, graphs = FALSE, assays = "RNA")
zf_myo_list <- SplitObject(zf_myocardium, split.by = 'group')

zf_myo_list <- lapply(X = zf_myo_list, FUN = function(x) {
    x <- NormalizeData(x)
    x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000)
})

features <- SelectIntegrationFeatures(object.list = zf_myo_list)

zf.anchors <- FindIntegrationAnchors(object.list = zf_myo_list, anchor.features = features)

zf_myo_int <- IntegrateData(anchorset = zf.anchors)
```
```{r}

DefaultAssay(zf_myo_int) <- "integrated"
zf_myo_int <- ScaleData(zf_myo_int, verbose = FALSE, vars.to.regress = 'percent.mt')
zf_myo_int <- RunPCA(zf_myo_int, npcs = 30, verbose = FALSE)
zf_myo_int <- RunUMAP(zf_myo_int, reduction = "pca", dims = 1:30)
zf_myo_int <- FindNeighbors(zf_myo_int, reduction = "pca", dims = 1:30)
zf_myo_int <- FindClusters(zf_myo_int, resolution = 0.5)
DimPlot(zf_myo_int, label = TRUE)

DimPlot(zf_myo_int, group.by = 'group')

```

```{r}
DefaultAssay(zf_myo_int) <- 'RNA'
FeaturePlot_scCustom(zf_myo_int, features = c('acta2','tbx2a'))
```
```{r}
zf_myo_int <- RunUMAP(zf_myo_int, reduction = "pca", dims = 1:30)
DimPlot(zf_myo_int, label = TRUE)
zf_myo_int <- RunUMAP(zf_myo_int, reduction = "pca", dims = 1:29)
DimPlot(zf_myo_int, label = TRUE)
zf_myo_int <- RunUMAP(zf_myo_int, reduction = "pca", dims = 1:28)
DimPlot(zf_myo_int, label = TRUE)
zf_myo_int <- RunUMAP(zf_myo_int, reduction = "pca", dims = 1:27)
DimPlot(zf_myo_int, label = TRUE)
zf_myo_int <- RunUMAP(zf_myo_int, reduction = "pca", dims = 1:26)
DimPlot(zf_myo_int, label = TRUE)
zf_myo_int <- RunUMAP(zf_myo_int, reduction = "pca", dims = 1:25)
DimPlot(zf_myo_int, label = TRUE)
zf_myo_int <- RunUMAP(zf_myo_int, reduction = "pca", dims = 1:24)
DimPlot(zf_myo_int, label = TRUE)
zf_myo_int <- RunUMAP(zf_myo_int, reduction = "pca", dims = 1:23)
DimPlot(zf_myo_int, label = TRUE)
zf_myo_int <- RunUMAP(zf_myo_int, reduction = "pca", dims = 1:22)
DimPlot(zf_myo_int, label = TRUE)
zf_myo_int <- RunUMAP(zf_myo_int, reduction = "pca", dims = 1:21)
DimPlot(zf_myo_int, label = TRUE)
zf_myo_int <- RunUMAP(zf_myo_int, reduction = "pca", dims = 1:20)
DimPlot(zf_myo_int, label = TRUE)
```

```{r}
DefaultAssay(myocardium) <- "RNA"
myo_markers <- FindAllMarkers(myocardium, only.pos = TRUE)
write.csv(myo_markers, file = 'myo_markers.csv')
```

```{r}
FeaturePlot_scCustom(myocardium, features = 'hey2')
```

```{r}
VlnPlot(myocardium, features = c('myl7','actc1a','tbx5a','gata6','mef2d','actn1','acta2','myh10','notch3'), split.by = 'species',stack = TRUE, flip = TRUE)
VlnPlot(heart_filtered, features = clust4_tf, split.by = 'species',stack = TRUE, flip = TRUE)

```

```{r}
heart_filtered <- readRDS('heart_filtered.rds')
```

```{r}
DimPlot(heart_filtered, label = TRUE)
FeaturePlot_scCustom(heart_filtered, features = 'myl4')
```

```{r}
clust4_markers <- filter(myo_markers, cluster == 4)
clust4_markers <- clust4_markers$gene

tf_df <- read.delim(file = '/Users/claytoncarey/Downloads/transcriptional_regulators.5 (1).txt')
tf_df <- tf_df$nanog

matching <- clust4_markers %in% tf_df

clust4_tf <- clust4_markers[matching]

clust4_tf
```

```{r}
library(scDblFinder)


heart.sce <- as.SingleCellExperiment(heart_filtered)

heart.sce <- scDblFinder(heart.sce)

heart.conv <- as.Seurat(heart.sce)
```
```{r}
myo_colors <- c("#fdbf6f", "#b2df8a", "#FFA07A","#fb9a99")
myocardium <- subset(myocardium, idents = 4, invert = TRUE)
DefaultAssay(myocardium) <- "integrated"
myocardium <- ScaleData(myocardium, assay = 'integrated')
myocardium <- RunPCA(myocardium, npcs = 30 )
myocardium <- RunUMAP(myocardium, dims = 1:25, min.dist = 0.1, n.epochs = 200)
myocardium <- FindNeighbors(myocardium, dims = 1:30, reduction = 'pca', n.tree = 500 )
myocardium <- FindClusters(myocardium, resolution = 0.15, algorithm = 2)
DimPlot(myocardium, label = TRUE, pt.size = 1, label.size = 6, cols = myo_colors) +NoLegend() +NoAxes()
DimPlot(myocardium, group.by = 'group', cols = vln_color)
DimPlot(myocardium, group.by = 'Phase')

```

```{r}
DefaultAssay(myocardium) <- 'RNA'
FeaturePlot_scCustom(myocardium, features= 'tbx5a') + NoAxes()
```

```{r}
DefaultAssay(myocardium) <- "RNA"
new_myo_markers <- FindAllMarkers(myocardium, min.pct = 0.2)
write.csv(new_myo_markers, file = 'new_myo_markers.csv')
```

```{r}
dittoFreqPlot(myocardium, "layer", sample.by = 'sample', group.by = 'species' ,color.panel = c("#D39234","#61A2DE"), boxplot.color = '#4F4F4F', jitter.size = 1.5) + NoLegend() +  theme(axis.title.x=element_blank()) + theme(plot.title = element_blank()) + ylab("Percent of cardiomyocytes")  +scale_y_continuous(n.breaks = 20)  

```
```{r}
myocardium@meta.data <- mutate(myocardium@meta.data, cell_type = case_when(
  seurat_clusters == 0 ~ "tCM1",
  seurat_clusters == 1 ~ "cCM1",
  seurat_clusters == 2 ~ "tCM2",
  seurat_clusters == 3 ~ "tCM3"
))
```

```{r}
myocardium@meta.data <- mutate(myocardium@meta.data, layer = case_when(
  seurat_clusters == 0 ~ "Trabecular",
  seurat_clusters == 1 ~ "Cortical",
  seurat_clusters == 2 ~ "Trabecular",
  seurat_clusters == 3 ~ "Trabecular"
))
```

```{r}
DimPlot(myocardium, group.by = 'layer')
```


```{r}
Idents(myocardium) <- 'layer'
DefaultAssay(myocardium) <- "RNA"
VlnPlot(myocardium, features = c('myl7','cmlc1','tbx5a','gata6','mef2d'), split.by = 'species', stack = TRUE, flip=TRUE)
```
```{r}
VlnPlot(myocardium, features = 'tbx5a', split.by = 'species')
```
```{r}
my_levels <- c("tCM1","tCM2","tCM3","cCM1")
myocardium@meta.data$cell_type <- factor(x = myocardium@meta.data$cell_type, levels = my_levels)
```

```{r}
DefaultAssay(myocardium) <- "RNA"
Idents(myocardium) <- "cell_type"
myo_dot_markers <- c('myl7','actc1a',"tbx5a","gata6","mef2d","acta2","actn1","hey2")
DotPlot(myocardium, features = myo_dot_markers, scale = TRUE) +
  geom_point(aes(size=pct.exp), shape = 21, colour="black", stroke=0.5) +
  scale_colour_viridis(option="plasma", direction = -1) +
  guides(size=guide_legend(override.aes=list(shape=21, colour="black", fill="white"))) + theme(axis.text.x =    element_text(angle =45,hjust = 1)) + theme(legend.title = element_text( size = 8))
```


```{r}

Idents(myocardium) <- 'group'

trabCM_md <- subset(myocardium, subset = layer == "Trabecular" & species == 'medaka')
trabCM_zf <- subset(myocardium, subset = layer == "Trabecular" & species == 'zebrafish')

cortCM_md <- subset(myocardium, subset = layer == "Cortical" & species == 'medaka')
cortCM_zf <- subset(myocardium, subset = layer == "Cortical" & species == 'zebrafish')


zf_cort_3dpi <-FindMarkers(cortCM_zf, ident.1 = 'zebrafish_3dpi', ident.2 = 'zebrafish_uninjured', only.pos = TRUE)
md_cort_3dpi <-FindMarkers(cortCM_md, ident.1 = 'medaka_3dpi', ident.2 = 'medaka_uninjured', only.pos = TRUE)

write.csv(zf_cort_3dpi, file = "zf_cort_3dpi_deg.csv")
write.csv(md_cort_3dpi, file = "md_cort_3dpi_deg.csv")

zf_trab_3dpi <-FindMarkers(trabCM_zf, ident.1 = 'zebrafish_3dpi', ident.2 = 'zebrafish_uninjured', only.pos = TRUE)
md_trab_3dpi <-FindMarkers(trabCM_md, ident.1 = 'medaka_3dpi', ident.2 = 'medaka_uninjured', only.pos = TRUE)

write.csv(zf_trab_3dpi, file = "zf_trab_3dpi_deg.csv")
write.csv(md_trab_3dpi, file = "md_trab_3dpi_deg.csv")

```
```{r}
Idents(myocardium) <- "layer"
VlnPlot(myocardium, features = 'zbtb17', split.by = 'group', cols = vln_color, pt.size = 0)
```

```{r}
zf_uninj <- subset(heart_filtered, subset = sample == 'zebrafish_uninjured_1' | sample == 'zebrafish_uninjured_2')
DefaultAssay(zf_uninj) <- "RNA"
zf_uninj <- FindVariableFeatures(zf_uninj, selection.method = "vst", nfeatures = 2000)
zf_uninj <- ScaleData(zf_uninj, verbose = FALSE)
zf_uninj <- RunPCA(zf_uninj, npcs = 30, verbose = FALSE)
zf_uninj <- RunUMAP(zf_uninj, reduction = "pca", dims = 1:30)
zf_uninj <- FindNeighbors(zf_uninj, reduction = "pca", dims = 1:30)
zf_uninj <- FindClusters(zf_uninj, resolution = 0.5)
DimPlot(zf_uninj, label = TRUE)

DimPlot(zf_uninj, group.by = 'sample')
```

```{r}
FeaturePlot(zf_uninj, features = 'acta2', order = T)
```

```{r}
process_seurat <- function(data, mtcutoff = 20){
  so.data <- Read10X(data.dir = data)
  so <- CreateSeuratObject(counts = so.data, min.cells = 3)
  so[["percent.mt"]] <- PercentageFeatureSet(so, pattern = "^mt-")
  so <- subset(so, subset = nFeature_RNA > 200 & percent.mt < mtcutoff)
  so <- NormalizeData(so)
  return(so)
}

zf_uninj1 <- process_seurat(data = '/Users/claytoncarey/Documents/Seurat/19226X1_bc', mtcutoff = 30)
zf_uninj2 <- process_seurat(data = '/Users/claytoncarey/Documents/Seurat/19226X2_bc', mtcutoff = 30)

zf_uninj <- merge(zf_uninj1, y = zf_uninj2)

zf_uninj <- FindVariableFeatures(zf_uninj, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(zf_uninj)
zf_uninj <- ScaleData(zf_uninj, features = all.genes)
zf_uninj <- RunPCA(zf_uninj, features = VariableFeatures(object = zf_uninj))
zf_uninj <- FindNeighbors(zf_uninj, dims = 1:20)
zf_uninj <- FindClusters(zf_uninj, resolution = 0.5)
zf_uninj <- RunUMAP(zf_uninj, dims = 1:20)
DimPlot(zf_uninj, reduction = "umap", label = TRUE)
FeaturePlot_scCustom(zf_uninj, features = 'myl7')
VlnPlot(zf_uninj, features = 'percent.mt')

```
```{r}
FeaturePlot_scCustom(zf_uninj, features = c('acta2',"myl7","hey2","actn1"))
```


```{r}
zf_uninj1_data <- read10X(data.dir = '/Users/claytoncarey/Documents/Seurat/19226X1_bc')
zf_uninj2_data <- read10X(data.dir = '/Users/claytoncarey/Documents/Seurat/19226X2_bc')

zf_uninj1 <- CreateSeuratObject(zf_uninj1_data, min.cells = 3)
zf_uninj2 <- CreateSeuratObject(zf_uninj2_data, min.cells = 3)

zf_uninj1[["percent.mt"]] <- PercentageFeatureSet(pbmc, pattern = "^MT-")

```

```{r}
zf_uninj_myo <- subset(zf_uninj, idents = c(1,2,6,12))
zf_uninj_myo <- FindVariableFeatures(zf_uninj_myo, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(zf_uninj_myo)
zf_uninj_myo <- ScaleData(zf_uninj_myo, features = all.genes, vars.to.regress = 'percent.mt')
zf_uninj_myo <- RunPCA(zf_uninj_myo, features = VariableFeatures(object = zf_uninj_myo))
zf_uninj_myo <- FindNeighbors(zf_uninj_myo, dims = 1:20)
zf_uninj_myo <- FindClusters(zf_uninj_myo, resolution = 0.5)
zf_uninj_myo <- RunUMAP(zf_uninj_myo, dims = 1:20)
DimPlot(zf_uninj_myo)
FeaturePlot_scCustom(zf_uninj_myo, features = c('acta2','notch3','cxcl14','bcam'))
FeaturePlot_scCustom(zf_uninj_myo, features = 'percent.mt')
FeaturePlot_scCustom(zf_uninj_myo, features = 'acta2')
FeaturePlot_scCustom(zf_uninj_myo, features = 'hey2')


```
```{r}
zf_uninj_myo <- RunUMAP(zf_uninj_myo, dims = 1:20)
DimPlot(zf_uninj_myo)
zf_uninj_myo <- RunUMAP(zf_uninj_myo, dims = 1:21)
DimPlot(zf_uninj_myo)
zf_uninj_myo <- RunUMAP(zf_uninj_myo, dims = 1:22)
DimPlot(zf_uninj_myo)
zf_uninj_myo <- RunUMAP(zf_uninj_myo, dims = 1:23)
DimPlot(zf_uninj_myo)
zf_uninj_myo <- RunUMAP(zf_uninj_myo, dims = 1:24)
DimPlot(zf_uninj_myo)
zf_uninj_myo <- RunUMAP(zf_uninj_myo, dims = 1:25)
DimPlot(zf_uninj_myo)
zf_uninj_myo <- RunUMAP(zf_uninj_myo, dims = 1:26)
DimPlot(zf_uninj_myo)
zf_uninj_myo <- RunUMAP(zf_uninj_myo, dims = 1:27)
DimPlot(zf_uninj_myo)
zf_uninj_myo <- RunUMAP(zf_uninj_myo, dims = 1:28)
DimPlot(zf_uninj_myo)
zf_uninj_myo <- RunUMAP(zf_uninj_myo, dims = 1:29)
DimPlot(zf_uninj_myo)
zf_uninj_myo <- RunUMAP(zf_uninj_myo, dims = 1:30)
DimPlot(zf_uninj_myo)
```

```{r}
zf_uninj_myo <- RunUMAP(zf_uninj_myo, dims = 1:23, min.dist = 0.9, n.epochs = 500)
zf_uninj_myo <- FindClusters(zf_uninj_myo, resolution = 0.03, algorithm = 2)

DimPlot(zf_uninj_myo)
DimPlot(zf_uninj_myo, group.by = 'orig.ident')
FeaturePlot_scCustom(zf_uninj_myo, features = 'acta2')
FeaturePlot_scCustom(zf_uninj_myo, features = 'crb2a')
FeaturePlot_scCustom(zf_uninj_myo, features = 'gata6')

FeaturePlot_scCustom(zf_uninj_myo, features = c('acta2','hey2','bcam','crb2a'))

```
```{r}
zf_uninj_markers <- FindAllMarkers(zf_uninj_myo, only.pos = TRUE, min.pct = 0.2)
write.csv(zf_uninj_markers, file = 'zf_uninj_markers.csv')
```




```{r}
md_uninj1 <- process_seurat('/Users/claytoncarey/Documents/Seurat/Heart_cellranger_outs/md_uninj_3', 30)
md_uninj1@meta.data$sample <- "sample3"
md_uninj2 <- process_seurat(data = '/Users/claytoncarey/Documents/Seurat/Heart_cellranger_outs/md_uninj_4', mtcutoff = 30)
md_uninj2@meta.data$sample <- "sample4"

md_uninj <- merge(md_uninj1, y = md_uninj2)

md_uninj <- FindVariableFeatures(md_uninj, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(md_uninj)
md_uninj <- ScaleData(md_uninj, features = all.genes)
md_uninj <- RunPCA(md_uninj, features = VariableFeatures(object = md_uninj))
md_uninj <- FindNeighbors(md_uninj, dims = 1:20)
md_uninj <- FindClusters(md_uninj, resolution = 0.5)
md_uninj <- RunUMAP(md_uninj, dims = 1:20)
DimPlot(md_uninj, reduction = "umap", label = TRUE)
DimPlot(md_uninj, reduction = "umap", group.by = 'sample')
FeaturePlot_scCustom(md_uninj, features = 'myl7')
FeaturePlot_scCustom(md_uninj, features = 'acta2')
FeaturePlot_scCustom(md_uninj, features = 'pdgfra')


```

```{r}
md_uninj_myo <- subset(md_uninj, idents = c(2,6,15,16,18))
md_uninj_myo <- FindVariableFeatures(md_uninj_myo, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(md_uninj_myo)
md_uninj_myo <- ScaleData(md_uninj_myo, features = all.genes, vars.to.regress = 'percent.mt')
md_uninj_myo <- RunPCA(md_uninj_myo, features = VariableFeatures(object = md_uninj_myo))
md_uninj_myo <- FindNeighbors(md_uninj_myo, dims = 1:20)
md_uninj_myo <- FindClusters(md_uninj_myo, resolution = 0.5)
md_uninj_myo <- RunUMAP(md_uninj_myo, dims = 1:20)
DimPlot(md_uninj_myo)
DimPlot(md_uninj_myo, group.by = 'sample')
FeaturePlot_scCustom(md_uninj_myo, features = c('acta2','bcam','tbx2b','notch3'))
FeaturePlot_scCustom(md_uninj_myo, features = 'notch3')
```
```{r}
md_uninj_myo <- RunUMAP(md_uninj_myo, dims = 1:23, min.dist = 0.9, n.epochs = 500)
md_uninj_myo <- FindClusters(md_uninj_myo, resolution = 0.03, algorithm = 2)

DimPlot(md_uninj_myo)

FeaturePlot_scCustom(md_uninj_myo, features = c('tbx5a','gata6','tbx20'))
```


```{r}
zf2md <- read.csv(file = "/Users/claytoncarey/Documents/Seurat/zf.cm.markers/zf2md.csv")

zf2md_o2o <- filter(zf2md, type == 'ortholog_one2one' & score == 1)

zf2md_o2o_genes <- zf2md_o2o$zf_name

zf_uninj_markers$pct.diff <- zf_uninj_markers$pct.1 - zf_uninj_markers$pct.2

zf_uninj_markers

zf_primord_markers <- filter(zf_uninj_markers, cluster == 3 & pct.diff > 0.4)


zf_primord_markers_consereved <- filter(zf_primord_markers, gene %in% zf2md_o2o_genes)

zf_primord_markers_consereved

```

```{r}
zf_primord_markers_consereved_filtered <- filter(zf_primord_markers_consereved, pct.2 < 0.1)
zf_primord_markers_consereved_filtered <- zf_primord_markers_consereved_filtered$gene 
zf_primord_markers_consereved_filtered <- zf_primord_markers_consereved_filtered[!zf_primord_markers_consereved_filtered %in% c("cxcl14", "dipk1c", "gng13b",'acta2','lama5','pard6a')]

```

```{r}
DotPlot(zf_uninj_myo, features = zf_primord_markers_consereved_filtered)
DotPlot(md_uninj_myo, features = zf_primord_markers_consereved_filtered)

VlnPlot(md_uninj_myo, features = zf_primord_markers_consereved_filtered, stack = TRUE, flip = TRUE) + NoLegend()
VlnPlot(zf_uninj_myo, features = zf_primord_markers_consereved_filtered, stack = TRUE, flip = TRUE) + NoLegend()
```
```{r}
zf_cols <- c("#70FFE8", "#77ABE6", "#AA93FA", "#DB7BE3")
md_cols <- c("#FF5969","#E69063","#FAD27D","#E3DC66","#F6FA50")

DimPlot(md_uninj_myo, cols = md_cols, label = TRUE) + NoLegend() + NoAxes()
DimPlot(zf_uninj_myo, cols = zf_cols, label = TRUE) + NoLegend() + NoAxes()
```

```{r}
FeaturePlot_scCustom(zf_uninj_myo, features = c('myl7','acta2','crb2a','hey2'))
```

```{r}
fp1 <- FeaturePlot_scCustom(zf_uninj_myo, features = 'myl7') + NoAxes()
fp2 <- FeaturePlot_scCustom(zf_uninj_myo, features = 'acta2') + NoAxes()
fp3 <- FeaturePlot_scCustom(zf_uninj_myo, features = 'hey2') + NoAxes()
fp4 <- FeaturePlot_scCustom(zf_uninj_myo, features = 'clcn2a') + NoAxes()
fp5 <- FeaturePlot_scCustom(zf_uninj_myo, features = 'hspa12b') + NoAxes()
fp6 <- FeaturePlot_scCustom(zf_uninj_myo, features = 'anxa2a') + NoAxes()

grid.arrange(fp1,fp2,fp3,fp4,fp5,fp6, nrow = 2, ncol = 3)

```

```{r}
fp1 <- FeaturePlot_scCustom(md_uninj_myo, features = 'myl7') + NoAxes()
fp2 <- FeaturePlot_scCustom(md_uninj_myo, features = 'acta2') + NoAxes()
fp3 <- FeaturePlot_scCustom(md_uninj_myo, features = 'actn1') + NoAxes()
fp4 <- FeaturePlot_scCustom(md_uninj_myo, features = 'clcn2a') + NoAxes()
fp5 <- FeaturePlot_scCustom(md_uninj_myo, features = 'hspa12b') + NoAxes()
fp6 <- FeaturePlot_scCustom(md_uninj_myo, features = 'anxa2a') + NoAxes()

grid.arrange(fp1,fp2,fp3,fp4,fp5,fp6, nrow = 2, ncol = 3)

```