---
title: "Untitled"
author: "Clay Carey"
date: "2023-06-07"
output: html_document
---

```{r}
library(ggplot2)
library(Seurat)
library(dittoSeq)
library(Nebulosa)
library(dplyr)
library(gridExtra)
library(viridis)
library(scCustomize)
library(grid)
library(ggtext)
heart_filtered <- readRDS(file = '/Users/claytoncarey/Documents/Seurat/medaka_zebrafish_regeneration/heart_filtered.rds')
```

```{r}
Idents(heart_filtered) <- 'seurat_clusters'
DimPlot(heart_filtered, label = TRUE)
```

```{r}
endocardium <- subset(heart_filtered, idents = c(0,1,9,12,15,17,18,20))
```

```{r}
palette <- c("#a6cee3", "#fdbf6f", "#b2df8a", "#fb9a99", "#cab2d6", "#bcbddc","#ff9896", "#e377c2","#17becf", "#c6dcbd" , "#9edae5", "#8c96c6")

DefaultAssay(endocardium) <- "integrated"
endocardium <- ScaleData(endocardium)
endocardium <- RunPCA(endocardium, npcs = 30 )
endocardium <- RunUMAP(endocardium, dims = 1:28)
endocardium <- FindNeighbors(endocardium, dims = 1:20, reduction = 'pca', n.tree = 500, l2.norm = TRUE )
endocardium <- FindClusters(endocardium, resolution = .2)
DimPlot(endocardium, label = TRUE, cols = palette) +NoLegend() + NoAxes()
DimPlot(endocardium, split.by = 'species')
DimPlot(endocardium, group.by = 'group')
```

Remove cluster 10, which is contaminating T cells 
```{r}
Idents(endocardium) <- "seurat_clusters"
endocardium <- subset(endocardium, idents = 10, invert = TRUE)
```

```{r}

DefaultAssay(endocardium) <- "integrated"
endocardium <- ScaleData(endocardium)
endocardium <- RunPCA(endocardium, npcs = 30 )
endocardium <- RunUMAP(endocardium, dims = 1:28)
endocardium <- FindNeighbors(endocardium, dims = 1:27, reduction = 'pca', n.tree = 500, l2.norm = TRUE )
endocardium <- FindClusters(endocardium, resolution = .2)
DimPlot(endocardium, label = TRUE, cols = palette) +NoLegend() + NoAxes()
```

```{r}
endocardium@meta.data <- mutate(endocardium@meta.data, endo_cell_type = case_when(
  seurat_clusters == 0 ~ "eEC1",
  seurat_clusters == 1 ~ "eEC2",
  seurat_clusters == 2 ~ "eEC3",
  seurat_clusters == 3 ~ "fEC1",
  seurat_clusters == 4 ~ "eEC4",
  seurat_clusters == 5 ~ "cEC",
  seurat_clusters == 6 ~ "eEC5",
  seurat_clusters == 7 ~ "Mural",
  seurat_clusters == 8 ~ "fEC2",
  seurat_clusters == 9 ~ "fEC3",
  seurat_clusters == 10 ~ "lEC",
  TRUE ~ "Unclass"
))

endocardium@meta.data <- mutate(endocardium@meta.data, endo_cell_class = case_when(
  seurat_clusters == 0 ~ "eEC",
  seurat_clusters == 1 ~ "eEC",
  seurat_clusters == 2 ~ "eEC",
  seurat_clusters == 3 ~ "fEC",
  seurat_clusters == 4 ~ "eEC",
  seurat_clusters == 5 ~ "cEC",
  seurat_clusters == 6 ~ "eEC",
  seurat_clusters == 7 ~ "Mural",
  seurat_clusters == 8 ~ "fEC",
  seurat_clusters == 9 ~ "fEC",
  seurat_clusters == 10 ~ "lEC",
  TRUE ~ "Unclass"
))

endocardium@meta.data <- mutate(endocardium@meta.data, endo_cell_prolif = case_when(
  seurat_clusters == 0 ~ "other EC",
  seurat_clusters == 1 ~ "other EC",
  seurat_clusters == 2 ~ "other EC",
  seurat_clusters == 3 ~ "fEC",
  seurat_clusters == 4 ~ "other EC",
  seurat_clusters == 5 ~ "other EC",
  seurat_clusters == 6 ~ "other EC",
  seurat_clusters == 7 ~ "other EC",
  seurat_clusters == 8 ~ "fEC proliferating",
  seurat_clusters == 9 ~ "fEC proliferating",
  seurat_clusters == 10 ~ "other EC",
  TRUE ~ "Unclass"
))
```

```{r}
## 500 w x 500 h
Idents(endocardium) <- "endo_cell_type"
DimPlot(endocardium, cols = palette, label = TRUE, label.size = 6) + NoAxes() + NoLegend() 
```

```{r}
## height 300 width 550 
DefaultAssay(endocardium) <- "RNA"
Idents(endocardium) <- "endo_cell_class"
endo_markers <- c("tcf21","tbx18","fli1a","kdrl","f8","spock3",'col1a2','col1a1a','cavin1b','cldn5b','lyve1b','prox1a','pdgfrb','rgs5a')
DotPlot(endocardium, features = endo_markers, scale = TRUE) +
  geom_point(aes(size=pct.exp), shape = 21, colour="black", stroke=0.5) +
  scale_colour_viridis(option="plasma") +
  guides(size=guide_legend(override.aes=list(shape=21, colour="black", fill="white"))) + theme(axis.text.x = element_text(angle =45,hjust = 1)) + theme(legend.title = element_text( size = 8)) + ylab(element_blank()) + xlab(element_blank())

```

```{r}
epicardium <- subset(heart_filtered, idents = c(5,10,21))
```


```{r}
cols <- c("#8dd3c7", "#d9d9d9","#fb8072", "#fdb462")
DefaultAssay(epicardium) <- "integrated"
epicardium <- ScaleData(epicardium)
epicardium <- RunPCA(epicardium, npcs = 30 )
epicardium <- RunUMAP(epicardium, dims = 1:27, min.dist = 0.15, n.epochs = 200)
epicardium <- FindNeighbors(epicardium, dims = 1:27, reduction = 'pca', n.tree = 500 )
epicardium <- FindClusters(epicardium, resolution = 0.15)

epicardium@meta.data <- mutate(epicardium@meta.data, epicardium_class = case_when(
  seurat_clusters == 0 ~ "cEP1",
  seurat_clusters == 1 ~ "cEP2",
  seurat_clusters == 2 ~ "fEP",
  seurat_clusters == 3 ~ "zEP"
))

epicardium@meta.data <- mutate(epicardium@meta.data, epicardium_type_class = case_when(
  seurat_clusters == 0 ~ "cEP",
  seurat_clusters == 1 ~ "cEP",
  seurat_clusters == 2 ~ "fEP",
  seurat_clusters == 3 ~ "zEP"
))
Idents(epicardium) <- "epicardium_class"
#500 x 500 
DimPlot(epicardium, label = TRUE, pt.size = 1, cols = cols, label.size = 6) +NoLegend() +NoAxes()
```
```{r}

my_levels <- c("cEP","fEP","zEP")
epicardium@meta.data$epicardium_type_class <- factor(x = epicardium@meta.data$epicardium_type_class, levels = my_levels)

DefaultAssay(epicardium) <- "RNA"
Idents(epicardium) <- "epicardium_type_class"
epi_dot_markers <- c('fli1a','kdrl','tcf21','tbx18','twist1b','postnb','col12a1b','cldnc','jam2b')
 DotPlot(epicardium, features = epi_dot_markers, scale = TRUE) +
  geom_point(aes(size=pct.exp), shape = 21, colour="black", stroke=0.5) +
  scale_colour_viridis(option="magma") +
  guides(size=guide_legend(override.aes=list(shape=21, colour="black", fill="white"))) + theme(axis.text.x = element_text(angle =45,hjust = 1)) + theme(legend.title = element_text( size = 8))+ ylab(element_blank()) + xlab(element_blank())

 
```




```{r}


my_levels <- c("zebrafish_uninjured","zebrafish_3dpi","zebrafish_14dpi","medaka_uninjured","medaka_3dpi","medaka_14dpi")
endocardium@meta.data$group <- factor(x = endocardium@meta.data$group, levels = my_levels)
epicardium@meta.data$group <- factor(x = epicardium@meta.data$group, levels = my_levels)                        

vln_color_pastel <- c("#B3BBFF","#A0F8FF","#8AB9D9","#FF9E8A","#FFE8C0","#FFBFBD")

# Create a text grob
zf_gorb <- textGrob("Zebrafish (d.p.i.)", x = unit(.26, "npc"), y = unit(-1.4, "cm"), just = "center", gp = gpar(fontsize = 16))
zf_line <- linesGrob(x = unit(c(0.05, 0.47), "npc"), y = unit(c(-1, -1), "cm"), gp = gpar(col = "black", lwd = 3))

md_gorb <- textGrob("Medaka (d.p.i.)", x = unit(0.74, "npc"), y = unit(-1.4, "cm"), just = "center", gp = gpar(fontsize = 16))
md_line <- linesGrob(x = unit(c(0.53, 0.95), "npc"), y = unit(c(-1, -1), "cm"), gp = gpar(col = "black", lwd = 3))


p1 <- dittoFreqPlot(endocardium, "endo_cell_class", sample.by = 'sample', group.by = 'group' ,vars.use = 'fEC',color.panel = vln_color_pastel, boxplot.color = '#4F4F4F', jitter.size = 1.5) + NoLegend() +  theme(axis.title.x=element_blank()) + theme(plot.title = element_blank()) + ylab("Proportion of Endothelial Cells") +
  NoLegend() +
  theme(axis.title.y.left =  element_markdown(size = 14),  plot.margin = margin(1,1,1.5,1.2, "cm"),axis.title.x = element_blank(), plot.title = element_blank(), axis.text.x = element_markdown(angle = 0, hjust = 0.5, size = 14, color = "black",
                                        family = "Arial",
                                        align_widths = TRUE,
                                        padding = unit(c(2, 2), "pt"),
                                        linewidth = 0.5,
                                        linetype = "solid",
                                        box.colour = "black",
                                        fill  = vln_color_pastel)) +
  scale_x_discrete(labels = c("Uninj", "3", "14", "Uninj", "3", "14"))+
  geom_vline(xintercept = 3.5, linetype = "dashed", color = "darkgray") 




# Add the text grob to the plot using annotation_custom()
p2 <- p1 + annotation_custom(zf_gorb) + annotation_custom(md_gorb) + annotation_custom(zf_line) + annotation_custom(md_line) + coord_cartesian(clip = 'off')



p3 <- dittoFreqPlot(endocardium, "endo_cell_prolif", sample.by = 'sample', group.by = 'group' ,vars.use = 'fEC proliferating',color.panel = vln_color_pastel, boxplot.color = '#4F4F4F', jitter.size = 1.5) + NoLegend() +  theme(axis.title.x=element_blank()) + theme(plot.title = element_blank()) + ylab("Proportion of Endothelial Cells") +
  NoLegend() +
  theme(axis.title.y.left =  element_markdown(size = 14),  plot.margin = margin(1,1,1.5,1.2, "cm"),axis.title.x = element_blank(), plot.title = element_blank(), axis.text.x = element_markdown(angle = 0, hjust = 0.5, size = 14, color = "black",
                                        family = "Arial",
                                        align_widths = TRUE,
                                        padding = unit(c(2, 2), "pt"),
                                        linewidth = 0.5,
                                        linetype = "solid",
                                        box.colour = "black",
                                        fill  = vln_color_pastel)) +
  scale_x_discrete(labels = c("Uninj", "3", "14", "Uninj", "3", "14"))+
  geom_vline(xintercept = 3.5, linetype = "dashed", color = "darkgray") 

p4 <- p3 + annotation_custom(zf_gorb) + annotation_custom(md_gorb) + annotation_custom(zf_line) + annotation_custom(md_line) + coord_cartesian(clip = 'off')


p5 <- dittoFreqPlot(epicardium, "epicardium_class", sample.by = 'sample', group.by = 'group' ,vars.use = 'fEP',color.panel = vln_color_pastel, boxplot.color = '#4F4F4F', jitter.size = 1.5) + NoLegend() +  theme(axis.title.x=element_blank()) + theme(plot.title = element_blank()) + ylab("Proportion of Epicardial Cells") + theme(plot.title = element_text(size=22)) +
  NoLegend() +
  theme(axis.title.y.left =  element_markdown(size = 14),  plot.margin = margin(1,1,1.5,1.2, "cm"),axis.title.x = element_blank(), plot.title = element_blank(), axis.text.x = element_markdown(angle = 0, hjust = 0.5, size = 14, color = "black",
                                        family = "Arial",
                                        align_widths = TRUE,
                                        padding = unit(c(2, 2), "pt"),
                                        linewidth = 0.5,
                                        linetype = "solid",
                                        box.colour = "black",
                                        fill  = vln_color_pastel)) +
  scale_x_discrete(labels = c("Uninj", "3", "14", "Uninj", "3", "14"))+
  geom_vline(xintercept = 3.5, linetype = "dashed", color = "darkgray") 

p6 <- p5 + annotation_custom(zf_gorb) + annotation_custom(md_gorb) + annotation_custom(zf_line) + annotation_custom(md_line) + coord_cartesian(clip = 'off')

p2 + p4 + p6
## 1200 w x 600 h 
```

```{r}
Idents(endocardium) <- "endo_cell_type"
my_levels <- c("eEC1","eEC2","eEC3","eEC4","eEC5","cEC","lEC","fEC1",'fEC2',"fEC3","Mural")
endocardium@meta.data$endo_cell_type <- factor(x = endocardium@meta.data$endo_cell_type, levels = my_levels)
Idents(endocardium) <- "endo_cell_type"
endo_top <- c("krt94","romo1","btf3",'vcam1b','f8','thbs3a','hsp90aa1.2','mrc1a','egr1',"ndufa4","pln",'ckma','aqp1a.1','inhbab','ndnf','cxcl12b','cavin1b','plvapb','cxcl12a','cdh6','ccl38.1','ptx3a','cd9b','thbs1a','mcm5','mcm2','cdca7a','cenpf','aspm','mki67','rasl12','tpm1','notch3')
DotPlot(endocardium, features = endo_top, scale = TRUE) +
  geom_point(aes(size=pct.exp), shape = 21, colour="black", stroke=0.5) +
  scale_colour_viridis(option="plasma") +
  guides(size=guide_legend(override.aes=list(shape=21, colour="black", fill="white"))) + theme(axis.text.x =element_text(angle =45,hjust = 1)) + theme(legend.title = element_text( size = 8)) + ylab(element_blank()) + xlab(element_blank())

#750 W x 400 H 
Idents(epicardium) <- "epicardium_class"
my_levels <- c("cEP1","cEP2","zEP","fEP")
epicardium@meta.data$epicardium_class <- factor(x = epicardium@meta.data$epicardium_class, levels = my_levels)


epi_top <- c("itih5","hapln1a","pmp22a","mfap5","adh8a","tfa","pcolcea","jam2b","serpine3","podxl","cldnc","tmsb1",'col12a1a',"col11a1b","col12a1b",'postna')
DotPlot(epicardium, features = epi_top, scale = TRUE) +
  geom_point(aes(size=pct.exp), shape = 21, colour="black", stroke=0.5) +
  scale_colour_viridis(option="plasma") +
  guides(size=guide_legend(override.aes=list(shape=21, colour="black", fill="white"))) + theme(axis.text.x =element_text(angle =45,hjust = 1)) + theme(legend.title = element_text( size = 8)) + ylab(element_blank()) + xlab(element_blank())

```



```{r}
Idents(endocardium) <- "endo_cell_type"
Idents(epicardium) <- "epicardium_class"
leg <- theme(legend.position = "bottom",  # Place the legend below the plot
        legend.box = "horizontal",  # Arrange legend items horizontally
        legend.key.width = unit(.3, "cm"),  # Set the width of the legend key
        legend.key.height = unit(0.125, "cm"), # Set the height of the legend key
        legend.text = element_text(size = 9)) #set size of legend text


p1 <- FeaturePlot_scCustom(endocardium, "col1a2", label = TRUE) + NoAxes() + leg
p2 <- FeaturePlot_scCustom(endocardium, "col12a1a") + NoAxes() + leg
p3 <- FeaturePlot_scCustom(endocardium, "col5a1") + NoAxes() + leg
p4 <- FeaturePlot_scCustom(endocardium, "postnb") + NoAxes() + leg
p5 <- FeaturePlot_scCustom(endocardium, "postna") + NoAxes() + leg
p6 <- FeaturePlot_scCustom(endocardium, "twist1b") + NoAxes() + leg

f1 <- FeaturePlot_scCustom(epicardium, "col1a2", label = TRUE) + NoAxes() + theme(plot.title = element_blank()) + leg 
f2 <- FeaturePlot_scCustom(epicardium, "col12a1a") + NoAxes() + theme(plot.title = element_blank()) + leg
f3 <- FeaturePlot_scCustom(epicardium, "col5a1") + NoAxes() + theme(plot.title = element_blank()) + leg
f4 <- FeaturePlot_scCustom(epicardium, "postnb") + NoAxes() + theme(plot.title = element_blank()) + leg
f5 <- FeaturePlot_scCustom(epicardium, "postna") + NoAxes() + theme(plot.title = element_blank()) + leg
f6 <- FeaturePlot_scCustom(epicardium, "twist1b") + NoAxes() + theme(plot.title = element_blank()) + leg

grid.arrange(p1,p2,p3,p4,p5,p6,f1,f2,f3,f4,f5,f6, ncol = 6, nrow = 2)

#1600w x 800 h
```

```{r}

DefaultAssay(endocardium) <- "RNA"
s.genes <- c("mcm6","cdc45","msh2","mcm5","pola1","mcm4","gmnn","rpa2","hells","e2f8","gins2","pcna","nasp","brip1","dscc1","dtl","cdca7a","chaf1b","usp1","slbp","rrm1","fen1","exo1","tyms","uhrf1")
g2m.genes <- c("tpx2","birc5a","g2e3","cbx5","ctcf","ttk","smc4","nek2","cenpf","CKS2","top2a","cdca8","nusap1","kif11","anp32e","lbr","ccnb2","hmgb2a","cdk1","cks1b","ckap5")
endocardium <- CellCycleScoring(endocardium, s.features = s.genes, g2m.features = g2m.genes, set.ident = FALSE, )
DimPlot(endocardium, group.by = 'Phase') + NoAxes() 

```

```{r}
collagens <- grep("^col\\d+", heart_filtered@assays$RNA@counts@Dimnames[[1]], value = TRUE)
collagens_expressed <- c()
for (gene in collagens){
  en_ncells <- sum(GetAssayData(object = endocardium, slot = "data")[gene,]>0)
  ep_ncells <- sum(GetAssayData(object = epicardium, slot = "data")[gene,]>0)
  if(en_ncells > 150 | ep_ncells > 150){collagens_expressed<- c(collagens_expressed, gene)}
  }
collagens_expressed

ep_collagen_dp <- DotPlot_scCustom(epicardium, features = collagens_expressed, scale = TRUE, group.by = 'group', flip_axes = TRUE) +
  geom_point(aes(size=pct.exp), shape = 21, colour="black", stroke=0.5) +
  scale_colour_viridis(option="plasma") +
  guides(size=guide_legend(override.aes=list(shape=21, colour="black", fill="white"))) + theme(axis.text.x =element_text(angle =45,hjust = 1)) + theme(legend.title = element_text( size = 8)) + ylab(element_blank()) + xlab(element_blank())

endo_collagen_dp <- DotPlot_scCustom(endocardium, features = collagens_expressed, scale = TRUE, group.by = 'group', flip_axes = TRUE) +
  geom_point(aes(size=pct.exp), shape = 21, colour="black", stroke=0.5) +
  scale_colour_viridis(option="plasma") +
  guides(size=guide_legend(override.aes=list(shape=21, colour="black", fill="white"))) + theme(axis.text.x =element_text(angle =45,hjust = 1)) + theme(legend.title = element_text( size = 8)) + ylab(element_blank()) + xlab(element_blank())

ep_collagen_dp
endo_collagen_dp
#350 x 700
```

```{r}
mmps <- grep("^mmp\\d+", heart_filtered@assays$RNA@counts@Dimnames[[1]], value = TRUE)
mmps
mmps_expressed <- c()
for (gene in mmps){
  en_ncells <- sum(GetAssayData(object = endocardium, slot = "data")[gene,]>0)
  ep_ncells <- sum(GetAssayData(object = epicardium, slot = "data")[gene,]>0)
  if(en_ncells > 150 | ep_ncells > 150){mmps_expressed<- c(mmps_expressed, gene)}
  }
mmps_expressed

ep_mmps_dp <- DotPlot_scCustom(epicardium, features = mmps_expressed, scale = TRUE, group.by = 'group', flip_axes = TRUE) +
  geom_point(aes(size=pct.exp), shape = 21, colour="black", stroke=0.5) +
  scale_colour_viridis(option="plasma") +
  guides(size=guide_legend(override.aes=list(shape=21, colour="black", fill="white"))) + theme(axis.text.x =element_text(angle =45,hjust = 1)) + theme(legend.title = element_text( size = 8)) + ylab(element_blank()) + xlab(element_blank())

endo_mmps_dp <- DotPlot_scCustom(endocardium, features = mmps_expressed, scale = TRUE, group.by = 'group', flip_axes = TRUE) +
  geom_point(aes(size=pct.exp), shape = 21, colour="black", stroke=0.5) +
  scale_colour_viridis(option="plasma") +
  guides(size=guide_legend(override.aes=list(shape=21, colour="black", fill="white"))) + theme(axis.text.x =element_text(angle =45,hjust = 1)) + theme(legend.title = element_text( size = 8)) + ylab(element_blank()) + xlab(element_blank())

ep_mmps_dp
endo_mmps_dp
```




```{r}
Idents(endocardium) <- "endo_cell_type"
Idents(epicardium) <- "epicardium_class"
leg <- theme(legend.position = "bottom",  # Place the legend below the plot
        legend.box = "horizontal",  # Arrange legend items horizontally
        legend.key.width = unit(.3, "cm"),  # Set the width of the legend key
        legend.key.height = unit(0.125, "cm"), # Set the height of the legend key
        legend.text = element_text(size = 9)) #set size of legend text


p1 <- FeaturePlot_scCustom(endocardium, "nrg1", label = TRUE) + NoAxes() + leg
p2 <- FeaturePlot_scCustom(endocardium, "aldh1a2") + NoAxes() + leg
p3 <- FeaturePlot_scCustom(endocardium, "cntf") + NoAxes() + leg
p4 <- FeaturePlot_scCustom(endocardium, "cxcl12a") + NoAxes() + leg


f1 <- FeaturePlot_scCustom(epicardium, "nrg1", label = TRUE) + NoAxes() + theme(plot.title = element_blank()) + leg 
f2 <- FeaturePlot_scCustom(epicardium, "aldh1a2") + NoAxes() + theme(plot.title = element_blank()) + leg
f3 <- FeaturePlot_scCustom(epicardium, "cntf") + NoAxes() + theme(plot.title = element_blank()) + leg
f4 <- FeaturePlot_scCustom(epicardium, "cxcl12a") + NoAxes() + theme(plot.title = element_blank()) + leg


grid.arrange(p1,p2,p3,p4,f1,f2,f3,f4, ncol = 4, nrow = 2)

#1600w x 800 h
```
```{r}
DefaultAssay(heart_filtered) <- "RNA"
Idents(heart_filtered) <- "cell_class"

leg <- theme(legend.position = "bottom",  # Place the legend below the plot
        legend.box = "horizontal",  # Arrange legend items horizontally
        legend.key.width = unit(.3, "cm"),  # Set the width of the legend key
        legend.key.height = unit(0.125, "cm"), # Set the height of the legend key
        legend.text = element_text(size = 9)) #set size of legend text


p1 <- FeaturePlot_scCustom(heart_filtered, "nrg1") + NoAxes() + leg
p2 <- FeaturePlot_scCustom(heart_filtered, "aldh1a2") + NoAxes() + leg
p3 <- FeaturePlot_scCustom(heart_filtered, "cntf") + NoAxes() + leg
p4 <- FeaturePlot_scCustom(heart_filtered, "cxcl12b") + NoAxes() + leg


grid.arrange(p1,p2,p3,p4, ncol = 4, nrow = 1)

#1600w x 400 h

```

```{r}
vln_color_pastel <- c("#B3BBFF","#A0F8FF","#8AB9D9","#FF9E8A","#FFE8C0","#FFBFBD")

make_stacked_vln <- function(so, gene1, gene2, celltype1, celltype2){
    # Create a text grob
    zf_gorb <- textGrob("Zebrafish (d.p.i.)", x = unit(.26, "npc"), y = unit(-1.4, "cm"), just = "center", gp = gpar(fontsize =       16))
    zf_line <- linesGrob(x = unit(c(0.05, 0.47), "npc"), y = unit(c(-1, -1), "cm"), gp = gpar(col = "black", lwd = 3))
    
    md_gorb <- textGrob("Medaka (d.p.i.)", x = unit(0.74, "npc"), y = unit(-1.4, "cm"), just = "center", gp = gpar(fontsize = 16))
    md_line <- linesGrob(x = unit(c(0.53, 0.95), "npc"), y = unit(c(-1, -1), "cm"), gp = gpar(col = "black", lwd = 3))
    
    
    p0 <- VlnPlot(so, features = gene1, group.by = 'group', idents = celltype1, cols = vln_color_pastel, pt.size = 0.0 )+NoLegend()       + theme(axis.title.y.left =  element_markdown(size = 14), plot.margin = margin(3,1,0,1, "cm"), axis.title.x =           element_blank(), plot.title = element_blank(), axis.text.x = element_blank())+
      geom_vline(xintercept = 3.5, linetype = "dashed", color = "darkgray") + ylab(paste0(celltype1, " ", gene1))
    
    
      
    p2 <- VlnPlot(so, features = gene2, group.by = 'group', idents = celltype2, cols = vln_color_pastel, pt.size = 0.0 ) +              NoLegend()  +
      theme(axis.title.y.left =  element_markdown(size = 14),axis.title.x = element_blank(),plot.margin = margin(1,1,1.5,1, "cm"),       plot.title = element_blank(), axis.text.x = element_markdown(angle = 0, hjust = 0.5, size = 14, color = "black",
                                            family = "Arial",
                                            align_widths = TRUE,
                                            padding = unit(c(2, 2), "pt"),
                                            linewidth = 0.5,
                                            linetype = "solid",
                                            box.colour = "black",
                                            fill  = vln_color_pastel)) +
      scale_x_discrete(labels = c("Uninj", "3", "14", "Uninj", "3", "14"))+
      geom_vline(xintercept = 3.5, linetype = "dashed", color = "darkgray")  + ylab(paste0(celltype2, " ", gene2))

    p3 <- p2 + annotation_custom(zf_gorb) + annotation_custom(md_gorb) + annotation_custom(zf_line) + annotation_custom(md_line) +     coord_cartesian(clip = 'off')


     grid.arrange(p0,p3, ncol = 1, nrow = 2)
}

Idents(endocardium) <- "endo_cell_class"
Idents(epicardium) <- "epicardium_type_class"
DefaultAssay(endocardium) <- "RNA"
DefaultAssay(epicardium) <- "RNA"

#500 w x 600 h
make_stacked_vln(so = endocardium, gene1 ='aldh1a2', gene2 ='aldh1a2',celltype1 = 'fEC',celltype2 = 'eEC')
make_stacked_vln(so = endocardium, gene1 ='cntf',gene2 ='cntf',celltype1 =  'fEC', celltype2 = 'eEC')
make_stacked_vln(so = epicardium, gene1 = 'cxcl12a', gene2 = 'cxcl12a', celltype1 =  'fEP', celltype2 =  'cEP')
make_stacked_vln(so = endocardium, gene1 ='apln',gene2 ='cxcr4a', celltype1 = 'cEC', celltype2 ='cEC')




```




```{r}
zep_vln <- function(gene){
VlnPlot(epicardium, features = gene, group.by = 'group', idents = 'zEP', cols = zf_color_pastel, pt.size = 0.0 ) +       NoLegend()  +
      theme(axis.title.y.left =  element_markdown(size = 14),axis.title.x = element_blank(),plot.margin = margin(1,1,1.5,1, "cm"),       plot.title = element_blank(), axis.text.x = element_markdown(angle = 0, hjust = 0.5, size = 14, color = "black",
                                            family = "Arial",
                                            align_widths = TRUE,
                                            padding = unit(c(2, 2), "pt"),
                                            linewidth = 0.5,
                                            linetype = "solid",
                                            box.colour = "black",
                                            fill  = zf_color_pastel)) +
      scale_x_discrete(labels = c("Uninj", "3", "14", "Uninj", "3", "14"))  + ylab(paste0(gene))
}

zep_vln('angpt1')
zep_vln('vegfd')
zep_vln('cxcl8a')

#400 x 275
```



