---
title: "Figure 2"
author: "Clay Carey"
date: "2023-06-13"
output: html_document
---

```{r}
library(ggplot2)
library(Seurat)
library(dittoSeq)
library(Nebulosa)
library(dplyr)
library(gridExtra)
library(viridis)
library(scCustomize)
library(pheatmap)
library(tibble)
library(ggtext)

heart_filtered <- readRDS(file = "/Users/claytoncarey/Documents/Seurat/medaka_zebrafish_regeneration/Final_code/heart_filtered.rds")

```

```{r}
isg_selected <- c("stat1a","isg15","rsad2","elof1","xaf1","ifit10","ifit12","stat1b",'irf9',"mxa","mxb",'mxc')

#create a seurat object for each tissue type based on previously added metadata
endothelium <- subset(heart_filtered, subset = cell_class == "Endothelial")
epicardium <- subset(heart_filtered, subset = cell_class == "Epicardium")
myocardium <- subset(heart_filtered, subset = cell_class == "Cardiomyocyte")
Leukocyte <- subset(heart_filtered, subset = cell_class == "Leukocyte")


#change the active identities to "group", which specifies the species and timepoint of each cell
Idents(endothelium) <- "group"
Idents(epicardium) <- "group"
Idents(myocardium) <- "group"
Idents(Leukocyte) <- "group"

#we extract expression values for selected genes with the averageexpression function for each tissue type
endothelium.avg <- AverageExpression(endothelium, features = isg_selected, assays = 'RNA')
epicardium.avg <- AverageExpression(epicardium, features = isg_selected, assays = 'RNA')
myocardium.avg <- AverageExpression(myocardium, features = isg_selected, assays = 'RNA')
Leukocyte.avg <- AverageExpression(Leukocyte, features = isg_selected, assays = 'RNA')

#convert to dataframe with expression data from RNA assay
endothelium.df <- as.data.frame(endothelium.avg$RNA)
myocardium.df <- as.data.frame(myocardium.avg$RNA)
epicardium.df <- as.data.frame(epicardium.avg$RNA)
Leukocyte.df <- as.data.frame(Leukocyte.avg$RNA)

#add prefix to col names to id source cells
endothelium.df <- rename_with(endothelium.df, ~paste0("Endothelium_", .x))
endothelium.df <- rownames_to_column(endothelium.df, var = 'gene')

myocardium.df <- rename_with(myocardium.df, ~paste0("Myocardium_", .x))
myocardium.df <- rownames_to_column(myocardium.df, var = 'gene')

epicardium.df <- rename_with(epicardium.df, ~paste0("Epicardium_", .x))
epicardium.df <- rownames_to_column(epicardium.df, var = 'gene')

Leukocyte.df <- rename_with(Leukocyte.df, ~paste0("Leukocyte_", .x))
Leukocyte.df <- rownames_to_column(Leukocyte.df, var = 'gene')

#Now we merge all the data into one dataframe 
isg.merge <- endothelium.df %>% left_join(epicardium.df, by = 'gene')  %>% left_join(Leukocyte.df, by = 'gene')  %>% left_join(myocardium.df, by = 'gene')

rownames(isg.merge) <- isg.merge$gene
isg.merge <- select(isg.merge, !gene)

isg.merge <-  select(isg.merge, -contains("medaka"), everything())

isg.merge
```

```{r}
# these are variables I set up to specify the formatting and colors used in the heatmap


zebrafish <- c("Zebrafish_Uninjured", "Zebrafish_3_d.p.i.", "Zebrafish_14_d.p.i.")
medaka <- c("Medaka_Uninjured", "Medaka_3_d.p.i.", "Medaka_14_d.p.i.")
repeated_vectors <- c(rep_len(zebrafish, 12), rep_len(medaka, 12))
colors_list <- c(Zebrafish_Uninjured = "#B3BBFF", Zebrafish_3_d.p.i. = "#A0F8FF", Zebrafish_14_d.p.i. = "#8AB9D9", Medaka_Uninjured = "#FF9E8A", Medaka_3_d.p.i. =  "#FFE8C0", Medaka_14_d.p.i.= "#FFBFBD")
colors_list_tissue <- c(Endothelium = "#CE85D4",Epicardium = "#9EEBAC", Leukocyte = "#5777EA", Myocardium = "#F6915D")



# create the formatting datafreame 
groupcodes1 <- data.frame(Tissue = rep(c("Endothelium","Epicardium","Leukocyte","Myocardium","Endothelium","Epicardium","Leukocyte","Myocardium"),c(3,3,3,3,3,3,3,3)), Group = repeated_vectors)

rownames(groupcodes1) = colnames(isg.merge)[1:ncol(isg.merge)]

#create the heatmap 
pheatmap(isg.merge, scale = 'row', na_col = 'grey',cluster_cols = FALSE, gaps_col = c(3,6,9,12,15,18,21,24),cluster_rows = TRUE, annotation_col = groupcodes1, show_colnames = FALSE, cellwidth = 20, cellheight = 20, annotation_colors = list(Group = colors_list, Tissue = colors_list_tissue), breaks=seq(-2, 3, length.out=101))

```

```{r}


zf_endo <- subset(heart_filtered, subset = species == 'zebrafish' & cell_class == "Endothelial")

my_levels <- c("zebrafish_uninjured","zebrafish_3dpi","zebrafish_14dpi")
zf_endo@meta.data$group <- factor(x = zf_endo@meta.data$group, levels = my_levels)



ifnphi_pos <- subset(zf_endo, subset = ifnphi1 > 0)
ifnphi_cells <- ifnphi_pos@meta.data
ifnphi_cells$ifnphi_pos <- "positive"
ifnphi_cells$cell_id <- rownames(ifnphi_cells)
ifnphi_cells <- select(ifnphi_cells, ifnphi_pos, cell_id)
all_meta <- zf_endo@meta.data
all_meta$cell_id <- row.names(all_meta)
all_meta <- left_join(all_meta, ifnphi_cells, by = 'cell_id')
row.names(all_meta) <- all_meta$cell_id

all_meta <- select(all_meta, -cell_id)
all_meta

endo_filt_ifn <- zf_endo
endo_filt_ifn@meta.data <- all_meta



zf_color_pastel <- c("#B3BBFF","#A0F8FF","#8AB9D9")

# Create a text grob
zf_gorb <- textGrob("Zebrafish (d.p.i.)", x = unit(.5, "npc"), y = unit(-1.4, "cm"), just = "center", gp = gpar(fontsize = 16))
zf_line <- linesGrob(x = unit(c(0.05, 0.95), "npc"), y = unit(c(-1, -1), "cm"), gp = gpar(col = "black", lwd = 3))



p1 <- dittoFreqPlot(endo_filt_ifn, "ifnphi_pos", sample.by = 'sample', group.by = 'group',color.panel = zf_color_pastel ,boxplot.color = '#4F4F4F', jitter.size = 1.5) + NoLegend() +  theme(axis.title.x=element_blank()) + theme(plot.title = element_blank()) + ylab("Proportion of endocardial cells expressing ifnphi1") +
  NoLegend() +
  theme(axis.title.y.left =  element_markdown(size = 14),  plot.margin = margin(1,1,1.5,1.2, "cm"),axis.title.x = element_blank(), plot.title = element_blank(), axis.text.x = element_markdown(angle = 0, hjust = 0.5, size = 14, color = "black",
                                        family = "Arial",
                                        align_widths = TRUE,
                                        padding = unit(c(2, 2), "pt"),
                                        linewidth = 0.5,
                                        linetype = "solid",
                                        box.colour = "black",
                                        fill  = zf_color_pastel)) +
  scale_x_discrete(labels = c("Uninj", "3", "14"))
   




# Add the text grob to the plot using annotation_custom()
p2 <- p1 + annotation_custom(zf_gorb) + annotation_custom(zf_line) + coord_cartesian(clip = 'off')

p2

## 400  W X 600 H 
```



```{r}
my_levels <- c('zebrafish_uninjured','zebrafish_3dpi','zebrafish_14dpi','medaka_uninjured','medaka_3dpi','medaka_14dpi')
heart_filtered@meta.data$group <- factor(x = heart_filtered@meta.data$group, levels = my_levels)
VlnPlot(heart_filtered, features = 'isg15', group.by = "cell_cluster",split.by = 'group', cols = vln_color_pastel, pt.size = 0)
```
```{r}
f1 <- FeaturePlot_scCustom(heart_filtered, features = 'ifnphi1') + NoAxes()
f2 <- FeaturePlot_scCustom(heart_filtered, features = 'ifng1') + NoAxes()
f3 <- FeaturePlot_scCustom(heart_filtered, features = 'ifng1r') + NoAxes()
f4 <- FeaturePlot_scCustom(heart_filtered, features = 'ifnphi2') + NoAxes()
f5 <- FeaturePlot_scCustom(heart_filtered, features = 'ifnphi3') + NoAxes()
f6 <- FeaturePlot_scCustom(heart_filtered, features = 'ifnphi4') + NoAxes()

grid.arrange(f1,f2,f3,f4,f5,f6, ncol = 3, nrow = 2)

```

