---
title: "Immune analysis - Figure 3"
author: "Clay Carey"
date: "2023-06-14"
output: html_document
---

```{r}
library(ggplot2)
library(Seurat)
library(dittoSeq)
library(Nebulosa)
library(dplyr)
library(scCustomize)
library(gridExtra)
library(gridtext)
library(grid)

heart_filtered <- readRDS(file = "heart_filtered.rds")

```

```{r}
Idents(heart_filtered) <- "seurat_clusters"
DimPlot(heart_filtered, label = TRUE)
```

```{r}
Idents(heart_filtered) <- "seurat_clusters"
immune <- subset(heart_filtered, idents = c(4,6,11,13,16))

immune.colors <- c("#8dd3c7", "#fccde5", "#a6cee3", "#fb8072", "#fdb462", "#b3de69", "#d9d9d9", "#bc80bd", "#ccebc5", "#ffed6f", "#8b8b8b")

DefaultAssay(immune) <- "integrated"

immune <- FindVariableFeatures(immune)
all.genes <- rownames(immune)
immune <- ScaleData(immune, features = all.genes, vars.to.regress = 'percent.mt')
immune <- RunPCA(immune, npcs = 30, features = VariableFeatures(object = immune))
immune <- FindNeighbors(immune, dims = 1:25, n.trees = 50)
immune <- FindClusters(immune, resolution = 0.05, algorithm = 2, method = 'igraph')
immune <- RunUMAP(immune, dims = 1:22, n.epochs = 500)

DimPlot(immune)

```
```{r}

immune@meta.data <- mutate(immune@meta.data, cell_ID = case_when(
  seurat_clusters == 0 ~ "MF1",
  seurat_clusters == 1 ~ "TL",
  seurat_clusters == 2 ~ "BL",
  seurat_clusters == 3 ~ "GN",
  seurat_clusters == 4 ~ "MF2",
))

Idents(immune) <- "cell_ID"
DimPlot(immune, cols = immune.colors, label = TRUE) + NoLegend() + NoAxes()
```

```{r}
vln_color_pastel <- c("#B3BBFF","#A0F8FF","#8AB9D9","#FF9E8A","#FFE8C0","#FFBFBD")


# Create a text grob
zf_gorb <- textGrob("Zebrafish (d.p.i.)", x = unit(.26, "npc"), y = unit(-1.4, "cm"), just = "center", gp = gpar(fontsize = 16))
zf_line <- linesGrob(x = unit(c(0.05, 0.47), "npc"), y = unit(c(-1, -1), "cm"), gp = gpar(col = "black", lwd = 3))

md_gorb <- textGrob("Medaka (d.p.i.)", x = unit(0.74, "npc"), y = unit(-1.4, "cm"), just = "center", gp = gpar(fontsize = 16))
md_line <- linesGrob(x = unit(c(0.53, 0.95), "npc"), y = unit(c(-1, -1), "cm"), gp = gpar(col = "black", lwd = 3))

Idents(immune) <- "seurat_clusters"

macrophages <- subset(immune, idents = c(0,4))

DefaultAssay(macrophages) <- "RNA"

my_levels <- c("zebrafish_uninjured","zebrafish_3dpi","zebrafish_14dpi","medaka_uninjured","medaka_3dpi","medaka_14dpi")
macrophages@meta.data$group <- factor(x = macrophages@meta.data$group, levels = my_levels)

p0 <- VlnPlot(macrophages, features = 'tnfa', group.by = 'group', idents = c(0,4), cols = vln_color_pastel, pt.size = 0.0 ) +NoLegend() + theme(axis.title.y.left =  element_markdown(size = 14), plot.margin = margin(3,1,0,1, "cm"), axis.title.x = element_blank(), plot.title = element_blank(), axis.text.x = element_blank())+
  geom_vline(xintercept = 3.5, linetype = "dashed", color = "darkgray") + ylab("macrophage tnfa")


  
p2 <- VlnPlot(macrophages, features = 'cd9b', group.by = 'group', idents =  c(0,4), cols = vln_color_pastel, pt.size = 0.0 ) + NoLegend()  +
  theme(axis.title.y.left =  element_markdown(size = 14),axis.title.x = element_blank(),plot.margin = margin(1,1,1.5,1, "cm"), plot.title = element_blank(), axis.text.x = element_markdown(angle = 0, hjust = 0.5, size = 14, color = "black",
                                        family = "Arial",
                                        align_widths = TRUE,
                                        padding = unit(c(2, 2), "pt"),
                                        linewidth = 0.5,
                                        linetype = "solid",
                                        box.colour = "black",
                                        fill  = vln_color_pastel)) +
  scale_x_discrete(labels = c("Uninj", "3", "14", "Uninj", "3", "14"))+
  geom_vline(xintercept = 3.5, linetype = "dashed", color = "darkgray")  + ylab("Macrophage cd9b")




# Add the text grob to the plot using annotation_custom()
 
  
p3 <- p2 + annotation_custom(zf_gorb) + annotation_custom(md_gorb) + annotation_custom(zf_line) + annotation_custom(md_line) + coord_cartesian(clip = 'off')


grid.arrange(p0,p3, ncol = 1, nrow = 2, padding = 0)
```

```{r}

vln_color_pastel <- c("#B3BBFF","#A0F8FF","#8AB9D9","#FF9E8A","#FFE8C0","#FFBFBD")

zf_macro_cols <- c("#B3BBFF","#A0F8FF","#8AB9D9","#A0F8FF","#8AB9D9")
md_macro_cols <- c("#FF9E8A","#FFE8C0","#FFBFBD","#FFE8C0","#FFBFBD")

ZFmpegpos <- c(368,265,895,717,467,319,327,2934,2900,2810,222,160,334,1311,2332,2405)
ZFcondition <- c("Uninjured_vent","Uninjured_vent","Uninjured_vent","Uninjured_vent","3 d.p.i_vent","3 d.p.i_vent","3 d.p.i_vent","3 d.p.i_scar","3 d.p.i_scar","3 d.p.i_scar","14 d.p.i_vent","14 d.p.i_vent","14 d.p.i_vent","14 d.p.i_scar","14 d.p.i_scar","14 d.p.i_scar")
ZFtotalmpeg <- data.frame(ZFmpegpos,ZFcondition)
ZFtotalmpeg$ZFcondition <- factor(ZFtotalmpeg$ZFcondition , levels=c("Uninjured_vent", "3 d.p.i_vent","14 d.p.i_vent","3 d.p.i_scar","14 d.p.i_scar"))

boxplot(ZFtotalmpeg$ZFmpegpos~ZFtotalmpeg$ZFcondition, data=ZFtotalmpeg, main = "Zebrafish",xlab="Condition",ylab="Number of mpeg+ cells/mm^2", col=zf_macro_cols,ylim = c(0,3000))

MDmpegpos <- c(1186,783,1159,227,340,150,751,1502,981,314,467,190,2159,1426,786)
MDcondition <- c("Uninjured_vent","Uninjured_vent","Uninjured_vent","3 d.p.i_vent","3 d.p.i_vent","3 d.p.i_vent","3 d.p.i_scar","3 d.p.i_scar","3 d.p.i_scar","14 d.p.i_vent","14 d.p.i_vent","14 d.p.i_vent","14 d.p.i_scar","14 d.p.i_scar","14 d.p.i_scar")

MDtotalmpeg <- data.frame(MDmpegpos,MDcondition)
MDtotalmpeg$MDcondition <- factor(MDtotalmpeg$MDcondition,levels = c("Uninjured_vent", "3 d.p.i_vent","14 d.p.i_vent","3 d.p.i_scar","14 d.p.i_scar"))

boxplot(MDtotalmpeg$MDmpegpos~MDtotalmpeg$MDcondition, data=MDtotalmpeg, main = "Medaka",xlab="Condition",ylab="Number of mpeg+ cells/mm^2", col=md_macro_cols,ylim = c(0,3000)) 


```

```{r}
uninj_col <- c("#B3BBFF","#FF9E8A")
Uninj_mpegpos <- c(368,265,895,717,1186,783,1159)
Uninj_condition <- c("Uninjured_zf","Uninjured_zf","Uninjured_zf","Uninjured_zf","Uninjured_md","Uninjured_md","Uninjured_md")
Uninj_totalmpeg <- data.frame(Uninj_mpegpos,Uninj_condition)
Uninj_totalmpeg$Uninj_condition <- factor(Uninj_totalmpeg$Uninj_condition , levels=c("Uninjured_zf", "Uninjured_md"))

boxplot(Uninj_totalmpeg$Uninj_mpegpos~Uninj_totalmpeg$Uninj_condition, data=Uninj_totalmpeg, main = "Macrophages",xlab="Condition",ylab="Number of mpeg+ cells/mm^2", col=uninj_col,ylim = c(0,1500))

# Subset the data for each condition
zf <- subset(Uninj_totalmpeg, Uninj_condition == "Uninjured_zf")
md <- subset(Uninj_totalmpeg, Uninj_condition == "Uninjured_md")

# Perform t-test
result <- t.test(zf$Uninj_mpegpos, md$Uninj_mpegpos, var.equal = FALSE)

# Print the result
print(result)
```

```{r}
uninj_col <- c("#B3BBFF","#FF9E8A")
lckpos <- c(85,188,126,379,222,694)
condition <- c("Uninjured_zf","Uninjured_zf","Uninjured_zf","Uninjured_md","Uninjured_md","Uninjured_md")
totallck <- data.frame(lckpos,condition)
totallck$condition <- factor(totallck$condition , levels=c("Uninjured_zf","Uninjured_md"))
boxplot(totallck$lckpos~totallck$condition, data=totallck, main = "T cells",xlab="Condition",ylab="Number lck+ cells/mm^2",col=uninj_col)

# Subset the data for each condition
zf <- subset(totallck, condition == "Uninjured_zf")
md <- subset(totallck, condition == "Uninjured_md")

# Perform t-test
result <- t.test(zf$lckpos, md$lckpos)

# Print the result
print(result)

```


```{r}

# Subset the data for "Uninjured_vent" condition
uninjured_vent <- MDtotalmpeg$MDmpegpos[MDtotalmpeg$MDcondition == "Uninjured_vent"]

# Perform pairwise t-tests
conditions <- levels(MDtotalmpeg$MDcondition)
conditions <- conditions[conditions != "Uninjured_vent"]  # Exclude "Uninjured_vent"

results <- list()

for (condition in conditions) {
  subset_data <- MDtotalmpeg$MDmpegpos[MDtotalmpeg$MDcondition == condition]
  test_result <- t.test(uninjured_vent, subset_data)
  results[[condition]] <- test_result
}

# Print the results
for (condition in conditions) {
  result <- results[[condition]]
  cat("Comparison between Medaka 'Uninjured_vent' and '", condition, "':\n")
  cat("p-value:", result$p.value, "\n")
  cat("\n")
}


# Subset the data for "Uninjured_vent" condition
uninjured_vent <- ZFtotalmpeg$ZFmpegpos[ZFtotalmpeg$ZFcondition == "Uninjured_vent"]

# Perform pairwise t-tests
conditions <- levels(ZFtotalmpeg$ZFcondition)
conditions <- conditions[conditions != "Uninjured_vent"]  # Exclude "Uninjured_vent"

results <- list()

for (condition in conditions) {
  subset_data <- ZFtotalmpeg$ZFmpegpos[ZFtotalmpeg$ZFcondition == condition]
  test_result <- t.test(uninjured_vent, subset_data)
  results[[condition]] <- test_result
}

# Print the results
for (condition in conditions) {
  result <- results[[condition]]
  cat("Comparison between Zebrafish 'Uninjured_vent' and '", condition, "':\n")
  cat("p-value:", result$p.value, "\n")
  cat("\n")
}


```


```{r}
library(ggplot2)
library(dplyr)

# Add Species column to ZFtotalmpeg and MDtotalmpeg
ZFtotalmpeg <- ZFtotalmpeg %>% mutate(Species = "Zebrafish")
MDtotalmpeg <- MDtotalmpeg %>% mutate(Species = "Medaka")

# Merge the data frames
totalmpeg <- bind_rows(ZFtotalmpeg, MDtotalmpeg)

# Set factor levels for condition
totalmpeg$condition <- factor(totalmpeg$condition,
                              levels = c("Uninjured", "3 d.p.i", "14 d.p.i", "3 d.p.i ", "14 d.p.i "))

# Create a grouped boxplot using ggplot2
ggplot(totalmpeg, aes(x = condition, y = ZFmpegpos, fill = Species)) +
  geom_boxplot(position = position_dodge(width = 0.75)) +
  labs(title = "Zebrafish and Medaka",
       x = "Condition",
       y = "Number mpeg+ cells/mm") +
  scale_fill_manual(values = c(zf_macro_cols, md_macro_cols)) +
  ylim(0, 3000) +
  geom_boxplot(data = totalmpeg, aes(x = condition, y = MDmpegpos, fill = Species),
               width = 0.75, position = position_dodge(width = 0.75))


```

```{r}

tnfa_pos <- subset(macrophages, subset = tnfa > 0)
tnfa_cells <- tnfa_pos@meta.data
tnfa_cells$tnfa_pos <- "positive"
tnfa_cells$cell_id <- rownames(tnfa_cells)
tnfa_cells <- select(tnfa_cells, tnfa_pos, cell_id)
all_meta <- macrophages@meta.data
all_meta$cell_id <- row.names(all_meta)
all_meta <- left_join(all_meta, tnfa_cells, by = 'cell_id')
row.names(all_meta) <- all_meta$cell_id

all_meta <- select(all_meta, -cell_id)
all_meta

macro_filt_tnfa <- macrophages
macro_filt_tnfa@meta.data <- all_meta

my_levels <- c("zebrafish_uninjured","zebrafish_3dpi","zebrafish_14dpi","medaka_uninjured","medaka_3dpi","medaka_14dpi")
macro_filt_tnfa@meta.data$group <- factor(x = macro_filt_tnfa@meta.data$group, levels = my_levels)


# Create a text grob
zf_gorb <- textGrob("Zebrafish (d.p.i.)", x = unit(.26, "npc"), y = unit(-1.4, "cm"), just = "center", gp = gpar(fontsize = 16))
zf_line <- linesGrob(x = unit(c(0.05, 0.47), "npc"), y = unit(c(-1, -1), "cm"), gp = gpar(col = "black", lwd = 3))

md_gorb <- textGrob("Medaka (d.p.i.)", x = unit(0.74, "npc"), y = unit(-1.4, "cm"), just = "center", gp = gpar(fontsize = 16))
md_line <- linesGrob(x = unit(c(0.53, 0.95), "npc"), y = unit(c(-1, -1), "cm"), gp = gpar(col = "black", lwd = 3))

Idents(macrophages) <- "seurat_clusters"


  
p2 <- dittoFreqPlot(macro_filt_tnfa, "tnfa_pos", sample.by = 'sample', group.by = 'group',color.panel = vln_color_pastel,boxplot.color = '#4F4F4F', jitter.size = 1.5) + NoLegend() +  theme(axis.title.x=element_blank()) + theme(plot.title = element_blank()) + ylab("Proportion of macrophages cells expressing tnfa")+ NoLegend()  +
  theme(axis.title.y.left =  element_markdown(size = 14),axis.title.x = element_blank(),plot.margin = margin(1,1,1.5,1, "cm"), plot.title = element_blank(), axis.text.x = element_markdown(angle = 0, hjust = 0.5, size = 14, color = "black",
                                        family = "Arial",
                                        align_widths = TRUE,
                                        padding = unit(c(2, 2), "pt"),
                                        linewidth = 0.5,
                                        linetype = "solid",
                                        box.colour = "black",
                                        fill  = vln_color_pastel)) +
  scale_x_discrete(labels = c("Uninj", "3", "14", "Uninj", "3", "14"))+
  geom_vline(xintercept = 3.5, linetype = "dashed", color = "darkgray")  




# Add the text grob to the plot using annotation_custom()
 
  
p3 <- p2 + annotation_custom(zf_gorb) + annotation_custom(md_gorb) + annotation_custom(zf_line) + annotation_custom(md_line) + coord_cartesian(clip = 'off')

p3

```

